# ██╗░░██╗░█████╗░██████╗░██╗██╗░░██╗████████╗███████╗░█████╗░███╗░░░███╗
# ██║░░██║██╔══██╗██╔══██╗██║╚██╗██╔╝╚══██╔══╝██╔════╝██╔══██╗████╗░████║
# ███████║███████║██████╔╝██║░╚███╔╝░░░░██║░░░█████╗░░███████║██╔████╔██║
# ██╔══██║██╔══██║██╔══██╗██║░██╔██╗░░░░██║░░░██╔══╝░░██╔══██║██║╚██╔╝██║
# ██║░░██║██║░░██║██║░░██║██║██╔╝╚██╗░░░██║░░░███████╗██║░░██║██║░╚═╝░██║
# ╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░╚═╝╚═╝╚═╝░░╚═╝░░░╚═╝░░░╚══════╝╚═╝░░╚═╝╚═╝░░░░░╚═╝
discord: "§aVoici le Lien discord: lien du discord"
site: "§aVoici le lien site: lien du site"